"""Scope strings for entity_json_kv (domain JSON migrated out of blob columns)."""

SCOPE_RUN_CONTEXT_EXTRA = "run_context_extra"
SCOPE_RUN_INPUT = "run_input"
SCOPE_STEP_INPUT = "step_input"
SCOPE_STEP_OUTPUT = "step_output"
SCOPE_CONTACT_SOURCE = "contact_source"
SCOPE_FOLLOW_UP_SOURCE = "follow_up_source"
SCOPE_FOLLOW_UP_OUTPUT = "follow_up_output"
SCOPE_RESEARCH_INPUT = "research_input"
SCOPE_RESEARCH_OUTPUT = "research_output"
SCOPE_ASSET_METADATA = "asset_metadata"
SCOPE_ASSET_PACKET = "asset_packet"
SCOPE_RUN_COMPANY_EXTRA = "run_company_extra"
